/**
 * All action types of the application will be here
 */

namespace ActionType {
    // 启动App
    export const APP_START_SETUP: 'APP_START_SETUP' = 'APP_START_SETUP'
    export const APP_REJECT_SETUP: 'APP_REJECT_SETUP' = 'APP_REJECT_SETUP'
    export const APP_FULFIL_SETUP: 'APP_FULFIL_SETUP' = 'APP_FULFIL_SETUP'

    // 通过ID获取文档
    export const DOCUMENT_START_FETCH: 'DOCUMENT_START_FETCH' = 'DOCUMENT_START_FETCH'
    export const DOCUMENT_FULFIL_FETCH: 'DOCUMENT_FULFIL_FETCH' = 'DOCUMENT_FULFIL_FETCH'
    export const DOCUMENT_REJECT_FETCH: 'DOCUMENT_REJECT_FETCH' = 'DOCUMENT_REJECT_FETCH'
    // 获取所有文档
    export const DOCUMENT_START_FETCH_ALL: 'DOCUMENT_START_FETCH_ALL' = 'DOCUMENT_START_FETCH_ALL'
    export const DOCUMENT_FULFIL_FETCH_ALL: 'DOCUMENT_FULFIL_FETCH_ALL' = 'DOCUMENT_FULFIL_FETCH_ALL'
    export const DOCUMENT_REJECT_FETCH_ALL: 'DOCUMENT_REJECT_FETCH_ALL' = 'DOCUMENT_REJECT_FETCH_ALL'
    // 保存文档
    export const DOCUMENT_START_SAVE: 'DOCUMENT_START_SAVE' = 'DOCUMENT_START_SAVE'
    export const DOCUMENT_FULFIL_SAVE: 'DOCUMENT_FULFIL_SAVE' = 'DOCUMENT_FULFIL_SAVE'
    export const DOCUMENT_REJECT_SAVE: 'DOCUMENT_REJECT_SAVE' = 'DOCUMENT_REJECT_SAVE'
    // 删除文档
    export const DOCUMENT_START_DROP: 'DOCUMENT_START_DROP' = 'DOCUMENT_START_DROP'
    export const DOCUMENT_FULFIL_DROP: 'DOCUMENT_FULFIL_DROP' = 'DOCUMENT_FULFIL_DROP'
    export const DOCUMENT_REJECT_DROP: 'DOCUMENT_REJECT_DROP' = 'DOCUMENT_REJECT_DROP'
    // 恢复文档
    export const DOCUMENT_START_RETRIE: 'DOCUMENT_START_RETRIE' = 'DOCUMENT_START_RETRIE'
    export const DOCUMENT_FULFIL_RETRIE: 'DOCUMENT_FULFIL_RETRIE' = 'DOCUMENT_FULFIL_RETRIE'
    export const DOCUMENT_REJECT_RETRIE: 'DOCUMENT_REJECT_RETRIE' = 'DOCUMENT_REJECT_RETRIE'
    // 清空垃圾箱 
    export const DOCUMENT_START_EMPTY_TRASH: 'DOCUMENT_START_EMPTY_TRASH' = 'DOCUMENT_START_EMPTY_TRASH'
    export const DOCUMENT_FULFIL_EMPTY_TRASH: 'DOCUMENT_FULFIL_EMPTY_TRASH' = 'DOCUMENT_FULFIL_EMPTY_TRASH'
    export const DOCUMENT_REJECT_EMPTY_TRASH: 'DOCUMENT_REJECT_EMPTY_TRASH' = 'DOCUMENT_REJECT_EMPTY_TRASH'
    // 新建文档
    export const DOCUMENT_START_CREATE: 'DOCUMENT_START_CREATE' = 'DOCUMENT_START_CREATE'
    export const DOCUMENT_FULFIL_CREATE: 'DOCUMENT_FULFIL_CREATE' = 'DOCUMENT_FULFIL_CREATE'
    export const DOCUMENT_REJECT_CREATE: 'DOCUMENT_REJECT_CREATE' = 'DOCUMENT_REJECT_CREATE'

}

export default ActionType